version: "3.4"

services:
  neurobase-frontend:
    image: neurobase/frontend-mockup
    build: .
    container_name: neurobase-frontend-mockup
    tty: true
    restart: on-failure
    ports:
      - "80:80"
