apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
      - name: secret-volume
        secret:
            secretName: env-secret
      containers:
      - name: frontend
        image: delgemoon/frontend:1.0 
        volumeMounts:
        - name: secret-volume
          mountPath: "/code"   
        ports:
        - containerPort: 80
