apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wf-api
  labels:
    app: wf-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wf-api
  template:
    metadata:
      labels:
        app: wf-api
    spec:
      containers:
        - name: wf-api
          image: delgemoon/wf_api:1.0
          env:
            - name: SQLSERVER_HOST
              valueFrom:
                secretKeyRef:
                  name: mssql
                  key: SQLSERVER_HOST
            - name: SQLSERVER_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql
                  key: SQLSERVER_SA_PASSWORD
          ports:
            - name: wf-api
              containerPort: 61511
