apiVersion: v1
kind: Service
metadata:  
  name: wf-client-service
spec:
  selector:    
    app: wf-client-ui
  type: LoadBalancer
  ports:  
  - name: http
    port: 80
    targetPort: 4200
    protocol: TCP