apiVersion: v1
kind: Service
metadata:  
  name: wf-designer-service
spec:
  selector:    
    app: wf-designer
  type: LoadBalancer
  ports:  
  - name: http
    port: 18098
    targetPort: 18098
    protocol: TCP