runtime: python
env: flex
entrypoint: gunicorn -b :$PORT app:app

runtime_config:
  python_version: 3

env_variables:
  FLASK_APP : app.py
  APP_SETTINGS: local
  DATABASE_URL : postgresql+psycopg2://postgres:unDG8lDxcvyh9Jl2@localhost:5432/user_mgr
  FLASK_ENV : development