// <auto-generated />

using System;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

using WF.Document.Data.DbContext;

namespace WF.Document.Data.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    [Migration("20180612014511_code2")]
    partial class code2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MXExchange.Wallet.Data.Models.OTItemHistoryEFModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment");

                    b.Property<DateTime>("Created");

                    b.Property<string>("CurrentState");

                    b.Property<string>("Executor");

                    b.Property<string>("NumberOfRequestDays");

                    b.Property<string>("RequestForUser");

                    b.Property<string>("Requester");

                    b.Property<string>("StartDate");

                    b.Property<Guid>("WorkflowId");

                    b.HasKey("Id");

                    b.ToTable("OTItemHistories");
                });

            modelBuilder.Entity("MXExchange.Wallet.Data.Models.UserEFModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserName");

                    b.Property<string>("UserRoles");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
